;;(package-initialize)
(setenv "SPACEMACSDIR" "~/.emacs.d/")
(setq dotspacemacs-filepath "~/.emacs.d/spacemacs.el")
(setq spacemacs-start-directory "~/.emacs.d/spacemacs/")
(load-file "~/.emacs.d/spacemacs/init.el")
